server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: ${AUTH_DB_URL}
    username: ${AUTH_DB_USER}
    password: ${AUTH_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

email-service:
  api:
    base-url: http://email-service:8086/api/v1/email/internal

verification:
  code:
    expiration-minutes: 10

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      access-token:
        expiration: ${JWT_ACCESS_EXPIRATION}
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION}

auth:
  oauth:
    google:
      allowed-audiences:
        - ${GOOGLE_WEB_CLIENT_ID}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:${EUREKA_ADMIN_PASSWD}@eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
