server:
  port: 8083

spring:
  application:
    name: list-service

  datasource:
    url: ${LIST_DB_URL:jdbc:postgresql://ep-floral-paper-acot5jab-pooler.sa-east-1.aws.neon.tech:5432/list_db?sslmode=require}
    username: ${LIST_DB_USER}
    password: ${LIST_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

content-service:
  api:
    base-url: http://content-service:8082/api/v1/content/internal

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:${EUREKA_ADMIN_PASSWD}@eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
