server:
  port: 8080
  forward-headers-strategy: none

spring:
  application:
    name: gateway

  threads:
      virtual:
        enabled: true

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**
            - id: content-service-internal-block
              uri: no://op
              order: -1
              predicates:
                - Path=/api/v1/content/internal/**
              filters:
                - SetStatus=403
            - id: content-service
              uri: lb://content-service
              order: 0
              predicates:
                - Path=/api/v1/content/**
            - id: list-service
              uri: lb://list-service
              predicates:
                - Path=/api/v1/list/**
            - id: feedback-service
              uri: lb://feedback-service
              predicates:
                - Path=/api/v1/feedback/**
            - id: user-service-internal-block
              uri: no://op
              order: -1
              predicates:
                - Path=/api/v1/users/internal/**
              filters:
                - SetStatus=403
            - id: user-service
              uri: lb://user-service
              order: 0
              predicates:
                - Path=/api/v1/users/**
            - id: email-service-internal-block
              uri: no://op
              order: -1
              predicates:
                - Path=/api/v1/email/internal/**
              filters:
                - SetStatus=403
            - id: search-service
              uri: lb://search-service
              predicates:
                - Path=/api/v1/search/**

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
    service-token:
      secret-key: ${SERVICE_JWT_SECRET}
      expiration: 3m
      cache-ttl: 150s

user-service:
  api:
    base-url: ${USER_SERVICE_BASE_URL:http://user-service:8085/api/v1/users/internal}

eureka:
  client:
    registry-fetch-interval-seconds: 10
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:${EUREKA_ADMIN_PASSWD}@eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
