server:
  port: 8085

spring:
  application:
    name: user-service

  jackson:
      mapper:
        accept-case-insensitive-enums: true

  data:
    web:
      pageable:
        one-indexed-parameters: true

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  datasource:
    url: ${USER_DB_URL:jdbc:postgresql://ep-floral-paper-acot5jab-pooler.sa-east-1.aws.neon.tech:5432/user_db?sslmode=require}
    username: ${USER_DB_USER}
    password: ${USER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
    service-token:
      secret-key: ${SERVICE_JWT_SECRET}
      expiration: 3m
      cache-ttl: 150s

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:${EUREKA_ADMIN_PASSWD}@eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

cloudinary:
  url: ${CLOUDINARY_URL}

content-service:
  api:
    base-url: ${CONTENT_SERVICE_BASE_URL:http://content-service:8082/api/v1/content/internal}

app:
  profile:
    favorites:
      max-size: 5
