server:
  port: 8761

spring:
  application:
    name: eureka-server

  security:
    user:
      name: admin
      password: ${EUREKA_ADMIN_PASSWD:eureka_test_password}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
