server:
  port: 8086

spring:
  application:
    name: email-service

  messages:
    basename: messages
    encoding: UTF-8

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
    service-token:
      secret-key: ${SERVICE_JWT_SECRET}
      expiration: 3m
      cache-ttl: 150s


resend:
  api:
    base-url: https://api.resend.com
    key: ${RESEND_API_KEY}
  mail:
    from: "WatchNext <noreply@watch-next.app>"

email:
  rate-limit:
    cooldown-seconds: 60
    max-per-hour: 5

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:${EUREKA_ADMIN_PASSWD}@eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
