name: CI WatchNext

on:
  push:
    branches: ["main"]
    tags:
      - "*-v*"

jobs:
  # 1. Detecta que carpetas cambiaron
  changes:
    runs-on: ubuntu-latest
    outputs:
      auth: ${{ steps.filter.outputs.auth }}
      content: ${{ steps.filter.outputs.content }}
      list: ${{ steps.filter.outputs.list }}
      feedback: ${{ steps.filter.outputs.feedback }}
      user: ${{ steps.filter.outputs.user }}
      email: ${{ steps.filter.outputs.email }}
      gateway: ${{ steps.filter.outputs.gateway }}
      eureka: ${{ steps.filter.outputs.eureka }}
      search: ${{ steps.filter.outputs.search }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            auth:
              - 'auth-service/**'
              - 'common/**'
              - 'pom.xml'
              - '.github/workflows/ci.yml'
            content:
              - 'content-service/**'
              - 'common/**'
              - 'pom.xml'
              - '.github/workflows/ci.yml'
            list:
              - 'list-service/**'
              - 'common/**'
              - 'pom.xml'
              - '.github/workflows/ci.yml'
            feedback:
              - 'feedback-service/**'
              - 'common/**'
              - 'pom.xml'
              - '.github/workflows/ci.yml'
            user:
              - 'user-service/**'
              - 'common/**'
              - 'pom.xml'
              - '.github/workflows/ci.yml'
            email:
              - 'email-service/**'
              - 'common/**'
              - 'pom.xml'
              - '.github/workflows/ci.yml'
            gateway:
              - 'gateway/**'
              - 'common/**'
              - 'pom.xml'
              - '.github/workflows/ci.yml'
            eureka:
              - 'eureka-server/**'
              - 'common/**'
              - 'pom.xml'
              - '.github/workflows/ci.yml'
            search:
              - 'search-service/**'
              - 'common/**'
              - 'pom.xml'
              - '.github/workflows/ci.yml'

  # 2. Compila Auth Service (Solo si hubo cambios)
  build-auth:
    needs: changes
    if: ${{ needs.changes.outputs.auth == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"
      - name: Dar permisos a Maven
        run: chmod +x mvnw
      - name: Instalar root POM
        run: ./mvnw install -N
      - name: Compilar Auth Service
        run: ./mvnw -pl auth-service -am package

  # 3. Compila Content Service (Solo si hubo cambios)
  build-content:
    needs: changes
    if: ${{ needs.changes.outputs.content == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"
      - name: Dar permisos a Maven
        run: chmod +x mvnw
      - name: Instalar root POM
        run: ./mvnw install -N
      - name: Compilar Content Service
        run: ./mvnw -pl content-service -am package

  # 4. Compila List Service (Solo si hubo cambios)
  build-list:
    needs: changes
    if: ${{ needs.changes.outputs.list == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"
      - name: Dar permisos a Maven
        run: chmod +x mvnw
      - name: Instalar root POM
        run: ./mvnw install -N
      - name: Compilar List Service
        run: ./mvnw -pl list-service -am package

  # 5. Compila Feedback Service (Solo si hubo cambios)
  build-feedback:
    needs: changes
    if: ${{ needs.changes.outputs.feedback == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"
      - name: Dar permisos a Maven
        run: chmod +x mvnw
      - name: Instalar root POM
        run: ./mvnw install -N
      - name: Compilar Feedback Service
        run: ./mvnw -pl feedback-service -am package

  # 6. Compila User Service (Solo si hubo cambios)
  build-user:
    needs: changes
    if: ${{ needs.changes.outputs.user == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"
      - name: Dar permisos a Maven
        run: chmod +x mvnw
      - name: Instalar root POM
        run: ./mvnw install -N
      - name: Compilar User Service
        run: ./mvnw -pl user-service -am package

  # 7. Compila Email Service (Solo si hubo cambios)
  build-email:
    needs: changes
    if: ${{ needs.changes.outputs.email == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"
      - name: Dar permisos a Maven
        run: chmod +x mvnw
      - name: Instalar root POM
        run: ./mvnw install -N
      - name: Compilar Email Service
        run: ./mvnw -pl email-service -am package

  # 8. Compila Gateway (Solo si hubo cambios)
  build-gateway:
    needs: changes
    if: ${{ needs.changes.outputs.gateway == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"
      - name: Dar permisos a Maven
        run: chmod +x mvnw
      - name: Instalar root POM
        run: ./mvnw install -N
      - name: Compilar Gateway
        run: ./mvnw -pl gateway -am package

  # 9. Compila Eureka Server (Solo si hubo cambios)
  build-eureka:
    needs: changes
    if: ${{ needs.changes.outputs.eureka == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"
      - name: Dar permisos a Maven
        run: chmod +x mvnw
      - name: Instalar root POM
        run: ./mvnw install -N
      - name: Compilar Eureka Server
        run: ./mvnw -pl eureka-server -am package

  # 10. Compila Search Service (Solo si hubo cambios)
  build-search:
    needs: changes
    if: ${{ needs.changes.outputs.search == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"
      - name: Dar permisos a Maven
        run: chmod +x mvnw
      - name: Instalar root POM
        run: ./mvnw install -N
      - name: Compilar Search Service
        run: ./mvnw -pl search-service -am package
